### ISSUE TITLE
But FMV don't have subtitles!

### ISSUE THREAD

**Issue by RetroGameTalk** [theflyingzamboni/lodmods#1]
Hi, why include these videos without subtitles? https://www.romhacking.net/hacks/3188/
How can we understand what's being said i Audio is in Japanese and no subtitles?
I don't get it. When you make an undub you add subtitles, else is useless to add.

**Comment by theflyingzamboni** [comment]
That's just a mod to swap audio files from the Japanese version that another user originally released, and I "ported" to my modding system for completeness sake. Some people just prefer to have the Japanese voices regardless of subtitles, though it's not really my cup of tea. (There are gameplay differences between the versions, so having Japanese voices in the English game is still different than just playing the Japanese version beyond the text.)That's really the only reason I bothered including it at all. Adding subtitles to video in a PS1 game is a process I'm unfamiliar with, assuming it is possible, and I have too many other projects going on to look into it.

Since this doesn't really have anything to do with the software itself, I'm going to mark this issue as closed.
